#! /bin/sh

### BEGIN INIT INFO
# Provides:             <%= @sshd_name %><%= @suffix %>
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6	
# Short-Description:    OpenBSD Secure Shell server
### END INIT INFO

set -e

# <%= @ssh_init %><%= @suffix %>: start and stop the OpenBSD "secure shell(tm)" daemon

test -x <%= @sshd_binary %><%= @suffix %> || exit 0
( <%= @sshd_binary %><%= @suffix %> -\? 2>&1 | grep -q OpenSSH ) 2>/dev/null || exit 0

umask 022

export SSHD_OOM_ADJUST=-17
if test -f <%= @ssh_default %><%= @suffix %>; then
    . <%= @ssh_default %><%= @suffix %>
fi

. /lib/lsb/init-functions

if [ -n "$2" ]; then
    SSHD_OPTS="$SSHD_OPTS $2"
fi

# Are we running from init?
run_by_init() {
    ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
}

check_for_no_start() {
    # forget it if we're trying to start, and <%= @ssh_norun %><%= @suffix %> exists
    if [ -e <%= @ssh_norun %><%= @suffix %> ]; then 
	    if [ "$1" = log_end_msg ]; then
	        log_end_msg 0
	    fi
	    if ! run_by_init; then
	        log_action_msg "OpenBSD Secure Shell server not in use (<%= @ssh_norun %><%= @suffix %>)"
	    fi
	    exit 0
    fi
}

check_dev_null() {
    if [ ! -c /dev/null ]; then
	    if [ "$1" = log_end_msg ]; then
	        log_end_msg 1 || true
	    fi
	    if ! run_by_init; then
	        log_action_msg "/dev/null is not a character device!"
	    fi
	    exit 1
    fi
}

check_privsep_dir() {
    # Create the PrivSep empty dir if necessary
    if [ ! -d <%= @sshd_privdir %><%= @suffix %> ]; then
	    mkdir <%= @sshd_privdir %><%= @suffix %>
	    chmod 0755 <%= @sshd_privdir %><%= @suffix %>
    fi
}

check_config() {
    if [ ! -e <%= @ssh_norun %><%= @suffix %> ]; then
	    <%= @sshd_binary %><%= @suffix %> $SSHD_OPTS -t || exit 1
    fi
}

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
	check_privsep_dir
	check_for_no_start
	check_dev_null
	log_daemon_msg "Starting OpenBSD Secure Shell server" "<%= @sshd_name %><%= @suffix %>"
	if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/<%= @sshd_name %><%= @suffix %>.pid --exec <%= @sshd_binary %><%= @suffix %> -- $SSHD_OPTS; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
	;;
  stop)
	log_daemon_msg "Stopping OpenBSD Secure Shell server" "<%= @sshd_name %><%= @suffix %>"
	if start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/<%= @sshd_name %><%= @suffix %>.pid; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
	;;

  reload|force-reload)
	check_for_no_start
	check_config
	log_daemon_msg "Reloading OpenBSD Secure Shell server's configuration" "<%= @sshd_name %><%= @suffix %>"
	if start-stop-daemon --stop --signal 1 --quiet --oknodo --pidfile /var/run/<%= @sshd_name %><%= @suffix %>.pid --exec <%= @sshd_binary %><%= @suffix %>; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
	;;

  restart)
	check_privsep_dir
	check_config
	log_daemon_msg "Restarting OpenBSD Secure Shell server" "<%= @sshd_name %><%= @suffix %>"
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile /var/run/<%= @sshd_name %><%= @suffix %>.pid
	check_for_no_start log_end_msg
	check_dev_null log_end_msg
	if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/<%= @sshd_name %><%= @suffix %>.pid --exec <%= @sshd_binary %><%= @suffix %> -- $SSHD_OPTS; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
	;;

  try-restart)
	check_privsep_dir
	check_config
	log_daemon_msg "Restarting OpenBSD Secure Shell server" "<%= @sshd_name %><%= @suffix %>"
	set +e
	start-stop-daemon --stop --quiet --retry 30 --pidfile /var/run/<%= @sshd_name %><%= @suffix %>.pid
	RET="$?"
	set -e
	case $RET in
	    0)
		# old daemon stopped
		check_for_no_start log_end_msg
		check_dev_null log_end_msg
		if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/<%= @sshd_name %><%= @suffix %>.pid --exec <%= @sshd_binary %><%= @suffix %> -- $SSHD_OPTS; then
		    log_end_msg 0
		else
		    log_end_msg 1
		fi
		;;
	    1)
		# daemon not running
		log_progress_msg "(not running)"
		log_end_msg 0
		;;
	    *)
		# failed to stop
		log_progress_msg "(failed to stop)"
		log_end_msg 1
		;;
	esac
	;;

  status)
	status_of_proc -p /var/run/<%= @sshd_name %><%= @suffix %>.pid <%= @sshd_binary %><%= @suffix %> sshd && exit 0 || exit $?
	;;

  *)
	log_action_msg "Usage: <%= @ssh_init %><%= @suffix %> {start|stop|reload|force-reload|restart|try-restart|status}"
	exit 1
esac

exit 0
